<div class="row">
    <div id="sobre-box">
        <h4>Sobre</h4>
        <p>
            Este site foi desenvolvido com o intuito 
            de ser utilizado como projeto em meu 
            <a href="https://felipeanmo.github.io/Portfolio" target="_blank">portfólio</a>. 
            Esta aplicação web foi desenvolvida utilizando 
            tecnologias como HTML, CSS, JavaScript, PHP e SQL.

        </p>
    </div>
</div>